<?php

namespace Solustat\TimeSheetBundle\Repository;

/**
 * NurseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NurseRepository extends \Doctrine\ORM\EntityRepository
{
}
