<?php

namespace Solustat\TimeSheetBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPatients($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('p')->getQuery();
        $query->setFirstResult(($page-1) * $nbPerPage)->setMaxResults($nbPerPage);

        return new Paginator($query, true);
    }
}
