<?php

namespace Solustat\TimeSheetBundle\Repository;

/**
 * TypeCareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCareRepository extends \Doctrine\ORM\EntityRepository
{
}
