<?php

namespace Solustat\TimeSheetBundle\Repository;

/**
 * VisitTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitTimeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllVisitsTime()
    {
        $result = $this->createQueryBuilder('v')
            ->getQuery()
            ->getArrayResult();

        return $result;
    }
}
